<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;


class ImageTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('images')->insert([
            [
                'id' => 1,
                'user_id' => 3,
                'checkpoint_id' => 2,
                'name' => 'cool looking old car',
                'path' => 'images/3_admin/cFfAt40yAXWCAt27IkZadzE0C3m90ZysPRaolXB9.png',
                'seed' => 3396715813,
                'positivePrompt' => 'car',
                'negativePrompt' => NULL,
                'public' => 1,
                'description' => 'description of a cool looking old car',
                'created_at' => '2024-06-17 02:58:49',
                'updated_at' => '2024-06-17 02:58:49',
            ],
            [
                'id' => 3,
                'user_id' => 3,
                'checkpoint_id' => 2,
                'name' => NULL,
                'path' => 'images/3_admin/rfkgp55dgXeL7gG9TZ0SZr9Yhiflbx3CTigX1jS2.png',
                'seed' => 2878794633,
                'positivePrompt' => 'closeup award winning photo of wolf, perfect environment, extremely detailed, dark shot',
                'negativePrompt' => '(octane render, render, drawing, anime, bad photo, bad photography:1.3), (worst quality, low quality, blurry:1.2), (bad teeth, deformed teeth, deformed lips), (bad anatomy, bad proportions:1.1), (deformed iris, deformed pupils), (deformed eyes, bad eyes), (deformed face, ugly face, bad face), (deformed hands, bad hands, fused fingers), morbid, mutilated, mutation, disfigured',
                'public' => 1,
                'description' => NULL,
                'created_at' => '2024-06-17 03:01:59',
                'updated_at' => '2024-06-17 03:01:59',
            ],
            [
                'id' => 4,
                'user_id' => 3,
                'checkpoint_id' => 2,
                'name' => NULL,
                'path' => 'images/3_admin/sgVu0puaZNS9SMHgbhTUEJwzluzNXJKbPHm9Gjo9.png',
                'seed' => 263128822,
                'positivePrompt' => 'glowing crystals in the cave, refraction, translucent, illumination',
                'negativePrompt' => '(octane render, render, drawing, anime, bad photo, bad photography:1.3), (worst quality, low quality, blurry:1.2), (bad teeth, deformed teeth, deformed lips), (bad anatomy, bad proportions:1.1), (deformed iris, deformed pupils), (deformed eyes, bad eyes), (deformed face, ugly face, bad face), (deformed hands, bad hands, fused fingers), morbid, mutilated, mutation, disfigured',
                'public' => 1,
                'description' => NULL,
                'created_at' => '2024-06-17 03:13:38',
                'updated_at' => '2024-06-17 03:13:38',
            ],
            [
                'id' => 5,
                'user_id' => 3,
                'checkpoint_id' => 2,
                'name' => 'super cool robot',
                'path' => 'images/3_admin/Xm5fQGEc0FXtHKh9BkWlGSezqWpFTZXNn7exzAJl.png',
                'seed' => 1838204094,
                'positivePrompt' => 'cgi, high quality render of mecha robot, perfect environment, city, sci-fi, extremely detailed, dof, bokeh',
                'negativePrompt' => '(octane render, render, drawing, anime, bad photo, bad photography:1.3), (worst quality, low quality, blurry:1.2), (bad teeth, deformed teeth, deformed lips), (bad anatomy, bad proportions:1.1), (deformed iris, deformed pupils), (deformed eyes, bad eyes), (deformed face, ugly face, bad face), (deformed hands, bad hands, fused fingers), morbid, mutilated, mutation, disfigured',
                'public' => 1,
                'description' => NULL,
                'created_at' => '2024-06-17 03:14:38',
                'updated_at' => '2024-06-17 03:14:38',
            ],
            [
                'id' => 6,
                'user_id' => 3,
                'checkpoint_id' => 2,
                'name' => 'A',
                'path' => 'private/images/3_admin/IbCxWwFGBrnJF1p39xrwes1DGg3hYmfM33DCg9pY.png',
                'seed' => 3711817124,
                'positivePrompt' => 'a',
                'negativePrompt' => NULL,
                'public' => 0,
                'description' => NULL,
                'created_at' => '2024-06-17 03:38:46',
                'updated_at' => '2024-06-17 03:38:46',
            ],
            [
                'id' => 7,
                'user_id' => 1,
                'checkpoint_id' => 1,
                'name' => 'space photo',
                'path' => 'images/1_johndoe/AJxUVhJ3NPvbiYcvcmmPziwKEMsloTGjeTCF3OcG.png',
                'seed' => 2023573340,
                'positivePrompt' => 'score_9, score_8_up, score_7_up, score_6_up, outdoors, space landscape',
                'negativePrompt' => NULL,
                'public' => 1,
                'description' => NULL,
                'created_at' => '2024-06-17 03:42:52',
                'updated_at' => '2024-06-17 03:42:52',
            ],
            [
                'id' => 8,
                'user_id' => 1,
                'checkpoint_id' => 2,
                'name' => 'realistic flower',
                'path' => 'images/1_johndoe/ahAytwc253n0uyY2pPHbqP6B1hKqhumSGVu4mPHz.png',
                'seed' => 770308813,
                'positivePrompt' => 'a polaroid photo of a flower in a garden',
                'negativePrompt' => '(octane render, render, drawing, anime, bad photo, bad photography:1.3), (worst quality, low quality, blurry:1.2), (bad teeth, deformed teeth, deformed lips), (bad anatomy, bad proportions:1.1), (deformed iris, deformed pupils), (deformed eyes, bad eyes), (deformed face, ugly face, bad face), (deformed hands, bad hands, fused fingers), morbid, mutilated, mutation, disfigured',
                'public' => 1,
                'description' => NULL,
                'created_at' => '2024-06-17 03:45:57',
                'updated_at' => '2024-06-17 03:45:57',
            ],
            [
                'id' => 9,
                'user_id' => 1,
                'checkpoint_id' => 2,
                'name' => 'real dragon capted on camera',
                'path' => 'images/1_johndoe/pL50jaKWHWIAGFiC5puNu1cnRynq0liux22hfOUv.png',
                'seed' => 1299328827,
                'positivePrompt' => 'polaroid photo of a huge mountain, supper tall, snow on top, red dragon flying',
                'negativePrompt' => '(octane render, render, drawing, anime, bad photo, bad photography:1.3), (worst quality, low quality, blurry:1.2), (bad teeth, deformed teeth, deformed lips), (bad anatomy, bad proportions:1.1), (deformed iris, deformed pupils), (deformed eyes, bad eyes), (deformed face, ugly face, bad face), (deformed hands, bad hands, fused fingers), morbid, mutilated, mutation, disfigured',
                'public' => 1,
                'description' => NULL,
                'created_at' => '2024-06-17 03:56:57',
                'updated_at' => '2024-06-17 03:56:57',
            ],
            [
                'id' => 10,
                'user_id' => 1,
                'checkpoint_id' => 2,
                'name' => 'guy riding a turtle in space',
                'path' => 'images/1_johndoe/KhTBWVifRGNKAFclPWnonUrtSgZWMVBBcKMS66gB.png',
                'seed' => 3222264026,
                'positivePrompt' => 'a man in space, riding a tourtle, yellow turtle, with glasses',
                'negativePrompt' => '(octane render, render, drawing, anime, bad photo, bad photography:1.3), (worst quality, low quality, blurry:1.2), (bad teeth, deformed teeth, deformed lips), (bad anatomy, bad proportions:1.1), (deformed iris, deformed pupils), (deformed eyes, bad eyes), (deformed face, ugly face, bad face), (deformed hands, bad hands, fused fingers), morbid, mutilated, mutation, disfigured',
                'public' => 1,
                'description' => 'he is so cool',
                'created_at' => '2024-06-17 04:00:24',
                'updated_at' => '2024-06-17 04:00:24',
            ],
            [
                'id' => 11,
                'user_id' => 2,
                'checkpoint_id' => 2,
                'name' => 'serious kangaroo',
                'path' => 'private/images/2_janedoe/ADRQn9qn9PuFNJsxkMG5hFCXkeuFdB19pz9zpU3h.png',
                'seed' => 1314266757,
                'positivePrompt' => 'epic, kangaroo, masterpiece',
                'negativePrompt' => '(octane render, render, drawing, anime, bad photo, bad photography:1.3), (worst quality, low quality, blurry:1.2), (bad teeth, deformed teeth, deformed lips), (bad anatomy, bad proportions:1.1), (deformed iris, deformed pupils), (deformed eyes, bad eyes), (deformed face, ugly face, bad face), (deformed hands, bad hands, fused fingers), morbid, mutilated, mutation, disfigured',
                'public' => 0,
                'description' => NULL,
                'created_at' => '2024-06-17 04:19:42',
                'updated_at' => '2024-06-17 04:19:42',
            ],
            [
                'id' => 12,
                'user_id' => 2,
                'checkpoint_id' => 2,
                'name' => NULL,
                'path' => 'images/2_janedoe/e1Iu8T044H2XaOXtIL27NdwkyWsVElXajI1cA6Ih.png',
                'seed' => 3937500583,
                'positivePrompt' => 'oil painting, underwater image of a ancient city, glowing, by Greg Rutkowski',
                'negativePrompt' => '(octane render, render, drawing, anime, bad photo, bad photography:1.3), (worst quality, low quality, blurry:1.2), (bad teeth, deformed teeth, deformed lips), (bad anatomy, bad proportions:1.1), (deformed iris, deformed pupils), (deformed eyes, bad eyes), (deformed face, ugly face, bad face), (deformed hands, bad hands, fused fingers), morbid, mutilated, mutation, disfigured',
                'public' => 1,
                'description' => NULL,
                'created_at' => '2024-06-17 04:21:33',
                'updated_at' => '2024-06-17 04:21:35',
            ],
        ]);
    }
}
